### ISSUE TITLE
Tracking Task

### ISSUE THREAD

**Issue by ridhlab** [ridhlab/payment-residence-management#7]
- [x] House Occupant Store
- [x] Tambah data history occupant
- [x] Nambah data house occupant pada occupant yang sedang ditempati akan error
- [x] Nambah data house occupant pada rumah yang sedang ditempati akan error
- [x] Get Dropdown Occupant
- [x] Remove house occcupant
- [x] Tambah column `number_of_months` di tabel `payments` 
- [x] Bisa melihat historical house occupant
  - Buat api dari controller historical
  - Filter berdasarkan house_id
- [x] Get dropdown monthly fee
- [x] Get dropdown monthly_expenses filter by is_paid_monthly
- [x] Create occupant payment
  ```
    payload : {
        "houseOccupantId" : integer
        "payments" : {
            "type" : "fee" | "expenses",
            "monthlyExpenseId" : integer,
            "monthlyFeeId" : integer,
            "numberOfMonth" : integer
        }[]
    }
  ```
- [x] Buat endpoint untuk mengambil data payment yang sudah lunas, dan belum lunas berdasarkan house occupant.
- [x] Di FE, di tiap item dropdown, kasih penjelasan mana yang belum lunas. 
- [x] Default item payment yang pertama kali muncul adalah payment yang belum lunas bulan ini, serta kategori monthly fee atau monthly exxpense yang is paid monthly.
- [x] Tambah fungsionalitas berhenti menghuni
- [x] Tambah masa kontrak
- [x] Tambah create pengeluaran
    - [x] Buat endpoint untuk mendapatkan semua total pemasukan
- [x] Validasi pembayaran penghuni kontrak 
     - [x] Get bulan terakhir pembayaran dari suatu penghuni
- [x] Ubah add payment
    - [x] Test case langsung lunas [1, 1]
    - [x] Test case langsung lunas [1]
    - [x] Test case langsung lunas [12, 1]
    - [x] Test case langsung lunas [12, 6]

Frontend task
- [x] Module House
- [x] Module Occupant
- [x] Module Payment Fee
- [x] Module Payment Expense
- [x] Create House Occupant

Case Frontend Occupant
- [x] User bakal pergi ke halaman house occupant, untuk melihat rumah mana saja yang sudah terisi dan melihat laporan keuangannya. Filter : houses->is_occupied = true
- [x] Habis itu masuk detail, dan melihat informasi rumah dan penghuni. Filter : house_occupants->id = $id && house_occupants->is_still_occupant = true  
- [x] Di detail bakal ada tab untuk menampilkan history house occupant, dan juga tab untuk menampilkan history pembayaran dari occupant sekarang
- [x] Di tab tersebut button `tambah` yang gunanya untuk menambah pembayaran penghuni yang sdang aktif. Setelah button tersebut di klik, akan muncul modal beirisi pembayaran apa saja yang harus di bayar. Pembayaran monnthly_fee akan muncul paling atas, serta pembayaran monthly_expenses yang paid_monthly akan muncul dari awal. User bisa menambahkan monthly expenses. Dan setiap item pembayaran, terdapat berapa bulan penghuni bayar
